---
title: "TIME SERIES TP 2"
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: yes
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      comment = NA,
                      warning = NA,
                      fig.width=12,
                      fig.height = 6
                      )
```
<style>
div.blue pre {background-color:#ccffcc;}
div.blue pre.r{background-color:#ccffff;}

</style>
<div class='blue'>

```{r}
library(ggplot2)
library(astsa)
library(dplyr)
library(xts)
```

# EXERCISE 1

## Question 1

$$X_t=X_{t_1}+\epsilon_t,\quad X_0=0$$


```{r}
par(mfrow=c(1,2))
X=numeric()
X[1]=0
n<-500
for (k in 2:n) 
{
  X[k]=X[k-1]+rnorm(1)
}

plot.ts(X,col='steel blue',frame=FALSE)
acf(ts(X))
```

## Question 2

```{r}
diffX<-diff(X)
plot.ts(diffX,col='steel blue',frame=FALSE)
```

There is no trend and the autocorrelation is nearly zero.

```{r}
acf(diffX)
```


# EXERCISE 2

$$Y_t=0.25+0.75Y_{t-1}+\epsilon_t$$

## Question 1

```{r}
Y=numeric()
Y[1]=0
print(Y)
for (k in 2:n)
{
  Y[k]=0.25+0.75*Y[k-1]+rnorm(1)
}

plot.ts(Y,col='steel blue',frame=FALSE)
par(mfrow=c(1,2))
acf(ts(Y))
pacY<-pacf(Y)
pacY
```


We notice the autocorrelation in $t>1$ results in autocorrelation in $t=1$

## Question 2


```{r}
Y=numeric()
Y[1]=0
Y[2]=0.25
print(Y)
for (k in 3:(n+50))
{
  Y[k]=0.25+0.75*Y[k-1]+rnorm(1)
}
Y<-Y[-(1:50)]
plot.ts(Y,col='steel blue',frame=FALSE)
par(mfrow=c(1,2))
acf(ts(Y))
pacY<-pacf(Y)
pacY
```


# EXERCISE 3

## Question 1

$$X_t=Z(t)+0.75Z(t-1)\quad,Z\approx\mathcal{N}(0,1)$$

```{r}
set.seed(123)
Z<-rnorm(n+1)
X<-numeric()
for (k in 2:(n+1))
{
    X[k]=Z[k]+0.75*Z[k-1]
}
X<-X[-1]
X1<-stats::filter(rnorm(n+1),filter=c(1,0.75),method='convolution')
X1<-X1[-1]
plot(ts(X),col='steel blue',frame=FALSE)
#lines(ts(X1),col='red')
par(mfrow=c(1,2))
acf(X)
pacf(X)
```

